# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_orig', models.CharField(max_length=1024, verbose_name='Original Link')),
                ('link_short', models.CharField(max_length=1024, verbose_name='Short Link')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('use', models.IntegerField(default=0, verbose_name='CntIntUse')),
            ],
            options={
                'verbose_name': 'Short Url',
                'verbose_name_plural': 'Short Urls',
            },
        ),
    ]
